version: '3.8'
services:
  back:
    build: ./BACKEND/ownBang
    container_name: back
    env_file:
      - .env
    ports:
      - "8887:8887"
    volumes:
      - ${OPENVIDU_RECORDING_PATH}:${OPENVIDU_RECORDING_PATH}
    environment:
      - aws_accessKey=${AWS_ACCESSKEY}
      - aws_cloudfront=${AWS_CLOUDFRONT}
      - aws_region=${AWS_REGION}
      - aws_s3bucket=${AWS_S3BUCKET}
      - aws_secretKey=${AWS_SECRETKEY}
      - aws_stack_auto=${AWS_STACK_AUTO}
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - FFMPEG_PATH=${FFMPEG_PATH}
      - FFPROBE_PATH=${FFPROBE_PATH}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - OPENVIDU_SECRET=${OPENVIDU_SECRET}
      - OPENVIDU_URL=${OPENVIDU_URL}
      - PORT=${PORT}
      - KEY_STORE=${KEY_STORE}
      - KEY_STORE_PASSWORD=${KEY_STORE_PASSWORD}
      - KEY_STORE_TYPE=${KEY_STORE_TYPE}
      - KEY_ALIAS=${KEY_ALIAS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - S3_ROOMIMAGE_PATH=${S3_ROOMIMAGE_PATH}
      - VIDEO_RECORDINGS_PATH=${VIDEO_RECORDINGS_PATH}
      - S3_HLS_PATH=${S3_HLS_PATH}
      - S3_USERIMG_PATH=${S3_USERIMG_PATH}
      - ELASTIC_SEARCH_HOST=${ELASTIC_SEARCH_HOST}
      - ELASTIC_SEARCH_PORT=${ELASTIC_SEARCH_PORT}
    depends_on:
      - redis
      - elasticsearch
      - kibana

  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "8886:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 1

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"  # Elasticsearch의 기본 포트
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"  # Kibana의 기본 포트
    depends_on:
      - elasticsearch

  front:
    build: ./FRONT
    container_name: front
    ports:
      - "5442:80"
  
